name: Release Containers

on:
  #repository_dispatch:
  push:
    tags:
    - 'v*'

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:

    - name: Get Tag Name
      id: get_tag_name  
      uses: olegtarasov/get-tag@v1

    - name: Container Registry Login
      id: docker_login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Checkout
      id: checkout
      uses: actions/checkout@v1
      
    - name: Push and Package
      id: push_and_package
      run: |
        # Push images and package
        yarn install
        build/vscdc pack  --release ${{ steps.get_tag_name.outputs.tag }} \
                          --github-repo ${{ github.repository }} \
                          --registry ${{ secrets.REGISTRY }} \
                          --registry-path ${{ secrets.REGISTRY_BASE_PATH }} \
                          --stub-registry ${{ secrets.STUB_REGISTRY }} \
                          --stub-registry-path ${{ secrets.STUB_REGISTRY_BASE_PATH }}

        # Set an output with the resulting package name for upload
        PKG_PREFIX=$(node -p "require('./package.json').name")
        echo "::set-output name=package_name::$(ls $PKG_PREFIX-*.tgz)"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload NPM Package as Release Asset
      id: upload_release_asset 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ steps.push_and_package.outputs.package_name }}
        asset_name: ${{ steps.push_and_package.outputs.package_name }}
        asset_content_type: application/gzip 
