name: CI & Push "dev"

on: 
  repository_dispatch:
  push:
    branches: master
    paths:
      - ./containers/**/*
      - ./script-library/**/*

jobs:
  build:
    
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, 'Automated cgmanifest.json update')"
    
    steps:

    - name: Container Registry Login
      id: docker_login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Checkout
      id: checkout
      uses: actions/checkout@v1
      
    - name: Push "dev", Package, update CG manifest
      run: |
        # Push dev images and package
        set -e
        yarn install
        build/vscdc pack --release ${{ github.ref }} --github-repo ${{ github.repository }} --registry ${{ secrets.REGISTRY }} --registry-path ${{ secrets.REGISTRY_BASE_PATH }} --stub-registry ${{ secrets.STUB_REGISTRY }} --stub-registry-path ${{ secrets.STUB_REGISTRY_BASE_PATH }}
        mv ./vscode-dev-containers-*.tgz ./vscode-dev-containers-${{ github.sha }}.tgz
        
        # Update CG manifest
        build/vscdc cg --no-build --release ${{ github.ref }} --github-repo ${{ github.repository }} --registry ${{ secrets.REGISTRY }} --registry-path ${{ secrets.REGISTRY_BASE_PATH }}
        git config --global user.email "vscr-feedback@microsoft.com"
        git config --global user.name "CI"
        git add cgmanifest.json
        git commit -m 'Automated cgmanifest.json update'
        git push "https://ci:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" HEAD:${{ github.ref }}

    - name: Upload Package
      uses: actions/upload-artifact@v1.0.0
      with:
        name: vscode-dev-containers-${{ github.sha }}.tgz
        path: ./vscode-dev-containers-${{ github.sha }}.tgz
