name: Release Containers

on:
  push:
    tags:
    - 'v*'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v2

    - name: Get tag name
      id: get_tag_name
      run: echo ::set-output name=tag_name::${GITHUB_REF/refs\/tags\//}

    - name: run tests
      id: run_tests
      run: |
        set -e

        echo ${{ github.event.ref }}
        echo ${{ steps.get_tag_name.output.tag_name }}

