name: Troubleshooting

on: 
  push:
    branches: [ci-troubleshooting]
    paths:
      - '.github/workflows'

jobs:
  troubleshooting:
    name: Troubleshooting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v1

    - name: Run troubleshooting script
      id: troubleshooting_script
      run: |
        set -e
        export SVC_PRN=$(node -c 'console.log(JSON.parse(`${{ secrets.AZ_ACR_CREDS }}`).clientId)')
        export PRN_SECRET=$(node -c 'console.log(JSON.parse(`${{ secrets.AZ_ACR_CREDS }}`).clientSecret)')
        export TENANT=$(node -c 'console.log(JSON.parse(`${{ secrets.AZ_ACR_CREDS }}`).tenantId)')
        export SUB=$(node -c 'console.log(JSON.parse(`${{ secrets.AZ_ACR_CREDS }}`).subscriptionId)')

        az login --service-principal -u $SVC_PRN -p $PRN_SECRET --tenant $TENANT
        az account show
        az account list --refresh
